# Generated by Django 4.1.6 on 2023-02-12 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='uploads/', width_field='width_field')),
                ('width_field', models.PositiveIntegerField(default=0)),
                ('height_field', models.PositiveBigIntegerField(default=0)),
                ('telephone', models.CharField(blank=True, max_length=11)),
                ('level', models.CharField(blank=True, max_length=3)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
    ]
