# Generated by Django 4.1.6 on 2023-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_department_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(blank=True, choices=[('SEET', 'School of Eng. and Eng. Tech.'), ('SOS', 'School of Sci.'), ('SAAT', 'School of Agric. and Agric. Tech.'), ('SET', 'School of Environmental Tech.'), ('SEMS', 'School of Earth and Mineral Sci.'), ('SAMT', 'School of Management Tech.'), ('SHHT', 'School of Health and Health Tech.'), ('SOC', 'School of Computing')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('100', '100L'), ('200', '200L'), ('300', '300L'), ('400', '400L'), ('500', '500L')], max_length=3),
        ),
    ]
