# Generated by Django 4.1.6 on 2023-02-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('rooms', models.PositiveIntegerField()),
                ('pirce', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'hostels',
            },
        ),
    ]
