# Generated by Django 4.1.6 on 2023-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='rooms',
            new_name='beds',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='slug',
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
