# Generated by Django 4.1.6 on 2023-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_rename_rooms_hostel_beds_remove_hostel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='pirce',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
