# Generated by Django 4.1.6 on 2023-02-14 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentprofile_profile_pic'),
        ('hostels', '0003_alter_hostel_description_alter_hostel_pirce'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('N', 'Not Approved')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
            options={
                'db_table': 'hostel_apps',
            },
        ),
    ]
