# Generated by Django 4.1.6 on 2023-02-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_hostelapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
