# Generated by Django 4.1.6 on 2023-02-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_hostelapplication_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('N', 'Not Approved')], default='P', max_length=1),
        ),
    ]
